### ISSUE TITLE
can't exec 'analyze-cc'

### ISSUE THREAD

**Issue by yangshengtao** [rizsotto/scan-build#102]
When I use the command following: scan-build xcodebuild -workspace

Then error occur:
error: can't exec 'analyze-cc' (No such file or directory)
Command analyze-cc failed with exit code 71

**Comment by rizsotto** [comment]
Hey, thanks for the report. Could you elaborate some details of you installation? (What OS do you run? Which version of scan-build you are using? How did you installed? Do you use virtualenv? etc...)

**Comment by yangshengtao** [comment]
I run the source code of scan-build in master branch. OS is macOS Sierra.
the complete command is:
scan-build xcodebuild -workspace xx.xcworkspace -configuration Debug -scheme xx
the "xx" presents my project

**Comment by yangshengtao** [comment]
I change the code bellow:
# COMPILER_WRAPPER_CC = 'analyze-cc'
COMPILER_WRAPPER_CC = 'myPath/clang'
Then eliminate the error above, but I encounter other problem that compile_commands.json generated is empty

**Comment by yangshengtao** [comment]
What was the command how you have installed on your machine?
I installed the llvm in the website "https://clang.llvm.org/get_started.html",and build the llvm and clang.
Then scan-build is in the path "llvm_sourcePath/tools/clang/tools/scan-build-py/bin"

**Comment by rizsotto** [comment]
Oh, then you are at the wrong place! This project is not that project. Was that readme files was pointed you to report here? It shall not. (If that's the case, please open a bug report on Clang.)
If you want to use this project, install this tool as it is written in the README file. (Basically create a python virtual env and run `pip install scan-build`)
