### ISSUE TITLE
Question: How is analyze-build compared with `bear`?

### ISSUE THREAD

**Issue by doronbehar** [rizsotto/scan-build#103]
Hey @rizsotto,

I couldn't help but notice that you are the developer of both this project and https://github.com/rizsotto/Bear as well and more interestingly, the command `bear` seems to be doing the same thing as `analyze-build` from this repo, yet `analyze-build` worked better for me in the little experience I had with both of them.

**Comment by rizsotto** [comment]
Hey @doronbehar , thanks for your message. There is an overlap between the two projects, and I'm working on to fix that. :) `bear` suppose to create the compilation database, while `analyze-build` runs the Clang static analyzer against that database. `scan-build` is the one, which does both, and this is what I want to delete in the near future.
The reason to have `scan-build` was that this project was planed to get merged into Clang repository and replace the Perl implementation of `scan-build`. This work stopped, so no need to keep the overlapping functionality.
Feel free to reopen this ticket if you have more questions.

**Comment by doronbehar** [comment]
Cool, I hope to see it goes through :) You are the only savior of those of us who would like to have `compile_commands.json` file for their (usually) GNU automake based build system, which is crucial for integration with auto-completion tools like `YouCompleteMe`. I couldn't find a **better** alternative yet, thanks so much for your effort!
