### ISSUE TITLE
Bugs occurring at the same location can falsely appear as duplicates

### ISSUE THREAD

**Issue by cfsteefel** [rizsotto/scan-build#110]
If a second bug happens to have the same line number and path length as another bug, one will be hidden. For example, if a bug is flagged at the same location as a dead store, only the dead store will appear in index.html, despite the bug report's html being generated. It seems to me that the bug type should be included in the hash generation function in report.py.

**Comment by rizsotto** [comment]
Thanks for the report, will look at it soon.

**Comment by rizsotto** [comment]
Added the "bug type" to the hash function. Thanks for your hint.
