### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by lichanghong** [rizsotto/scan-build#118]
bash-3.2$ pip install scan-build
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting scan-build
  Using cached https://files.pythonhosted.org/packages/93/03/f012b6a20a6c8fcac54ebe985fc137d4e899e3b997881445bf69e4277384/scan-build-2.0.17.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/m0/b6__78jj2gjcgfxlbjmzmsm80000gn/T/pip-install-CK9HO0/scan-build/setup.py'"'"'; __file__='"'"'/private/var/folders/m0/b6__78jj2gjcgfxlbjmzmsm80000gn/T/pip-install-CK9HO0/scan-build/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/m0/b6__78jj2gjcgfxlbjmzmsm80000gn/T/pip-install-CK9HO0/scan-build/pip-egg-info
         cwd: /private/var/folders/m0/b6__78jj2gjcgfxlbjmzmsm80000gn/T/pip-install-CK9HO0/scan-build/
    Complete output (1 lines):
    error in scan-build setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected version spec in typing; python_version < "3.5" at ; python_version < "3.5"
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by rizsotto** [comment]
How can I help? If you open this ticket in order to get help, please provide more context.

See issue template what details are helpful to investigate.

**Comment by lichanghong** [comment]
> How can I help? If you open this ticket in order to get help, please provide more context.
> 
> See issue template what details are helpful to investigate.

Mac version is the newest, and i installed pip, as the method pip install scan-build, I got an error.

**Comment by rizsotto** [comment]
Thanks to come back... So, you are not running the tool, but trying to install it? Have you check which Python version you have, as the error message suggested? Do you have `virtualenv` or `virtualenvwrapper` installed? (That might help to run different version of Python installed and used on the same machine.)
