### ISSUE TITLE
Intercept-build failed with dyld: could not load inserted library

### ISSUE THREAD

**Issue by ljq1206** [rizsotto/scan-build#129]
I want to use intercept-build with `intercept-build make all` on my project. but it cause an Error
the details:
dyld: could not load inserted library '/var/folders/rn/plq877vx3tb08dxd7_nxqgzr0000gn/T/intercept-oq16o2vg/libear.dylib' because no suitable image found.  Did find:
	/var/folders/rn/plq877vx3tb08dxd7_nxqgzr0000gn/T/intercept-oq16o2vg/libear.dylib: incompatible cpu-subtype: 0x00000000 in /var/folders/rn/plq877vx3tb08dxd7_nxqgzr0000gn/T/intercept-oq16o2vg/libear.dylib
	/var/folders/rn/plq877vx3tb08dxd7_nxqgzr0000gn/T/intercept-oq16o2vg/libear.dylib: stat() failed with errno=1

Desktop : Mac mini 
Chip: M1(arm64)
OS : MacOS 11.0.1  
scan-build : 2.0.19
python : 3.9
LLVM : 8.0.1

I would like to know if it is caused by different architectures (because the error report shows incompatible CPU types), and whether this tool does not support my device. 
what shuould I do now?

**Comment by rizsotto** [comment]
Try [Bear](https://github.com/rizsotto/Bear) from [Homebrew](https://formulae.brew.sh/formula/bear) to generate the compilation database.

**Comment by ljq1206** [comment]
It works by using Bear to generate the compilation database. 
why does this happen?

**Comment by rizsotto** [comment]
I am happy that you could have the desired compilation database. Don't know the reason why this was not working.
