### ISSUE TITLE
on WIndows scan-build works but not analyze-build

### ISSUE THREAD

**Issue by JacobVarghese1992** [rizsotto/scan-build#130]
scan-build on individual files in compile_commands.json works but running analyze-build passing -cbd does not

https://stackoverflow.com/questions/71332292/how-do-i-use-analyze-build-to-perform-static-analysis-on-android-c-project

**Comment by rizsotto** [comment]
if you have a JSON compilation database (`compile_commands.json`), then call `clang-tidy` instead. (`clang-tidy` also runs the static analyzer, plus a few other checks.)

https://clang.llvm.org/extra/clang-tidy/
