### ISSUE TITLE
Nonfunctional with modified versions of GCC

### ISSUE THREAD

**Issue by CATboardBETA** [rizsotto/scan-build#131]
Hello. I'm using a modified version of gcc, called `x86_64-elf-g++`. Unfortunately, when I run `intercept-build make build` it outputs an empty json `[]` in compile_commands.json. 

My Makefile:
```make
CPPFLAGS = -Wall -fpic -ffreestanding -fno-stack-protector -fno-exceptions -fno-rtti -nostdinc -nostdlib -I./stdlib/
LDFLAGS = -nostdlib -T link.ld
STRIPFLAGS = -s -K mmio -K fb -K bootboot -K environment -K initstack

all: billiamos.x86_64.elf billiamos.aarch64.elf setup launch
build: billiamos.x86_64.elf billiamos.aarch64.elf

billiamos.x86_64.elf: kernel.cpp
	x86_64-elf-g++ $(CPPFLAGS) -mno-red-zone -c kernel.cpp -o kernel.o
	x86_64-elf-ld -r -b binary -o font.o font.psf
	x86_64-elf-ld $(LDFLAGS) kernel.o font.o -o billiamos.x86_64.elf
	x86_64-elf-strip $(STRIPFLAGS) billiamos.x86_64.elf
	x86_64-elf-readelf -hls billiamos.x86_64.elf >billiamos.x86_64.txt

billiamos.aarch64.elf: kernel.cpp
	aarch64-elf-g++ $(CPPFLAGS) -c kernel.cpp -o kernel.o
	aarch64-elf-ld -r -b binary -o font.o font.psf
	aarch64-elf-ld $(LDFLAGS) kernel.o font.o -o billiamos.aarch64.elf
	aarch64-elf-strip $(STRIPFLAGS) billiamos.aarch64.elf
	aarch64-elf-readelf -hls billiamos.aarch64.elf >billiamos.aarch64.txt

setup: billiamos.x86_64.elf billiamos.aarch64.elf BilliamOSconfig.json
	mv billiamos.x86_64.elf  ./init/boot/sys/core/billiamos.x86_64.elf
	mv billiamos.aarch64.elf ./init/boot/sys/core/billiamos.aarch64.elf
	mkbootimg BilliamOSconfig.json billiamos.img

launch: billiamos.img
	qemu-system-x86_64 billiamos.img

clean:
	rm *.o *.elf *.txt || true
```

Along with ./kernel.cpp, I also have ./stdlib/cstdio, ./stdlib/bits/types.h, etc.

I don't expect it to do anything with cstdio, but I would expect all the other headers I have in ./stdlib/ to work fine.

**Comment by rizsotto** [comment]
Hey @CATboardBETA , try use my other project Bear to generate the compilation database. It respects the `CC` and `CXX` environment variables to detect what is a compiler. But also has a config file to describe the tools your project is using.

Has not work on the project for a long while, because the `clang-check` is running the static analyzer against a compilation database very well.

But if my memory is not too bad, this tool also has a few command line options to specify the compilers to be recognized.

**Comment by CATboardBETA** [comment]
@rizsotto --use-cxx and --use-cc are unrecognized options when I run `bear --use-cxx x86_64-elf-g++ -- make build`. Am I missing something?

**Comment by rizsotto** [comment]
All of these programs `bear` or `scan-build` has a `--help` option to learn about what are the valid flags. Bear has several man pages too.

The `--use-cc` flags are on the `scan-build` command. Recent version of Bear has a configuration file for compilers to recognize.
