### ISSUE TITLE
Empty compile_commands.json using Arm Compiler with Make

### ISSUE THREAD

**Issue by jvela018** [rizsotto/scan-build#134]
Hi,

Here are the steps to reproduce:

__Download__: $pip install scan-build
__Terminal Command__: $ intercept-build make -j$(nproc)

__OS__
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

__Compiler__: Arm Compiler for Embedded 6.21

I also tried different variations including overriding the compiler so that:

```
intercept-build --verbose --override-compiler --use-cc <path-to-my-compiler> make -j$(nproc)
```

The verbose flag didn't output anything. Any pointers on how to proceed from here?

BR,

/Jon

**Comment by rizsotto** [comment]
Hey @jvela018 ,

please use Bear to generate the compilation database. (That tool is better maintained, and have more options to control what compilers to recognize.)

**Comment by jvela018** [comment]
Ok. I will move to Bear. I'll close this issue. Thanks
