### ISSUE TITLE
compile libear with `-arch i386` and `-arch x86_64` on 64bits architectures

### ISSUE THREAD

**Issue by rizsotto** [rizsotto/scan-build#49]

**Comment by rizsotto** [comment]
check `platform.machine()` for `x86_64`

**Comment by RumAngelov** [comment]
Sorry for reopening this issue, but I believe this could be put in the scan-build (or maybe even bear) Readmes. I've tried multiple tools, including bear, but scan-build works best. I ran into the issue of building an universal binary on macOS and it kept failing & was looking exactly for this. 

Thank you.
