### ISSUE TITLE
libear is using LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by rizsotto** [rizsotto/scan-build#76]
to support 32 and 64 bit libraries on linux, better to put the path for both libraries into LD_LIBRARY_PATH and LD_PRELOAD can contains 'libear.so'

**Comment by ryosa** [comment]
What do you exactly mean? Set the env variables before invoking scan-build?

**Comment by rizsotto** [comment]
Hey @ryosa it's a bit consfusing that you report Bear problem here on a different project.

**Comment by ryosa** [comment]
@rizsotto Sorry about that. Just posted it to Bear.
