### ISSUE TITLE
Log link commands

### ISSUE THREAD

**Issue by whisperity** [rizsotto/scan-build#80]
It has been discussed long ago by CMake developers to [not include link commands in their generated JSON](http://clang-developers.42468.n3.nabble.com/Extending-CMAKE-EXPORT-COMPILE-COMMANDS-td4024793.html). However, there are cases it would be nice to see the linkage connections between compiled objects, not just the compilation commands. (E.g. our other tool, [_CodeCompass_](http://github.com/Ericsson/CodeCompass) can work some extra magic if linkage information is also passed to it.)

However, neither a `compile_commands.json` generated by CMake, nor by `intercept-build` contains linkage data. This just a mere suggestion, that we should include (maybe only by turning on an extra optional argument) linkage data so tools could work them, if we are already intercepting the build toolchain.

**Comment by rizsotto** [comment]
Thanks for this improvement idea. It's not totally new, other projects were also requested this feature earlier. Went to the mailing list and [asked](http://clang-developers.42468.n3.nabble.com/compilation-db-question-td4054364.html) the related questions.

As you can see from the answer the linking is not totally alien from the concept of compilation database. But very little (or none) support for it in the current Clang tooling library. (I would call the compilation database parser in Clang very picky/strict.)

Currently I'm busy to merge this code into Clang repository. Would not implement this feature now. My other tool (Bear) can be a better place to have this feature. (But I'm focusing my effort on scan-build merge.) Sorry to let you down with it. I can put more effort into it, when there is a more generic driver from Clang side too. As far as I can see Manuel (one of the guy behind Clang tooling) is supporting it, but lack resource to implement it. (Be the change you want! ;))
