### ISSUE TITLE
Cross compile

### ISSUE THREAD

**Issue by maosuyun2009** [rizsotto/scan-build#96]
Hi, I want use it to generate compile database in my cross-compile project, My gcc is arm-none-eabi-gcc. After build complete compile_commands.json is empty when I run intercept-build make

**Comment by rizsotto** [comment]
Hey, thanks for the report! I am aware that scan-build has no good support of cross compilation at the intercept level. My plan to get rid of the intercept module from this project. Please look at [Bear](https://github.com/rizsotto/Bear) to generate the compilation database. The current overlapping functionality will be removed soon.
